<?php

namespace ElevenmxBundle\Repository;

/**
 * GestionstatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GestionstatusRepository extends \Doctrine\ORM\EntityRepository
{
}
