<?php

namespace ElevenmxBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GraphisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GraphisteRepository extends EntityRepository
{
}
