<?php

namespace ElevenmxBundle\Repository;

/**
 * NouveauGraphisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NouveauGraphisteRepository extends \Doctrine\ORM\EntityRepository
{
}
