elevenmx:
    resource: "@ElevenmxBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout

elevenmx_nouveaugraphiste:
    resource: "@ElevenmxBundle/Resources/config/routing/nouveaugraphiste.yml"
    prefix:   /nouveaugraphiste
