elevenmx_graphiste:
    resource: "@ElevenmxBundle/Resources/config/routing/graphiste.yml"
    prefix:   /graphiste

elevenmx_homepage:
    path:     /
    defaults: { _controller: ElevenmxBundle:Default:index }

elevenmx_redirection:
    path:     /redirection
    defaults: { _controller: ElevenmxBundle:Default:redirection }

elevenmx_sendMail:
    path:     /sendMail
    defaults: { _controller: ElevenmxBundle:Default:sendMail }

elevenmx_projet:
    resource: "@ElevenmxBundle/Resources/config/routing/projet.yml"
    prefix:   /projet

elevenmx_produit:
        resource: "@ElevenmxBundle/Resources/config/routing/produit.yml"
        prefix:   /produit

elevenmx_marque:
        resource: "@ElevenmxBundle/Resources/config/routing/marque.yml"
        prefix:   /marque


