elevenmx_graphiste:
    resource: "@ElevenmxBundle/Resources/config/routing/graphiste.yml"
    prefix:   /graphiste

elevenmx_homepage:
    path:     /
    defaults: { _controller: ElevenmxBundle:Default:index }

elevenmx_redirection:
    path:     /redirection
    defaults: { _controller: ElevenmxBundle:Default:redirection }

elevenmx_sendMail:
    path:     /sendMail
    defaults: { _controller: ElevenmxBundle:Default:sendMail }

elevenmx_projet:
    resource: "@ElevenmxBundle/Resources/config/routing/projet.yml"
    prefix:   /projet
<<<<<<< HEAD
=======



>>>>>>> f20953aafee3d612e227b49f31dc18eff5a8120f
