elevenmx_graphiste:
    resource: "@ElevenmxBundle/Resources/config/routing/graphiste.yml"
    prefix:   /graphiste

elevenmx_homepage:
    path:     /
    defaults: { _controller: ElevenmxBundle:Default:index }
