elevenmx_graphiste:
    resource: "@ElevenmxBundle/Resources/config/routing/graphiste.yml"
    prefix:   /graphiste

elevenmx_homepage:
    path:     /
    defaults: { _controller: ElevenmxBundle:Default:index }

elevenmx_redirection:
    path:     /redirection
    defaults: { _controller: ElevenmxBundle:Default:redirection }

elevenmx_sendMail:
    path:     /sendMail
    defaults: { _controller: ElevenmxBundle:Default:sendMail }

