ElevenmxBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: ElevenmxBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreProjet:
            type: string
            length: 255
            column: Titre_Projet
        client:
            type: string
            length: 255
            column: Client
        marque:
            type: string
            length: 255
            column: Marque
        produit:
            type: string
            length: 255
            column: Produit
        nomGraphiste:
            type: string
            length: 255
            column: Nom_Graphiste

    manyToOne:
        graphiste:
            targetEntity: ElevenmxBundle\Entity\Graphiste
            inversedBy: projets

    lifecycleCallbacks: {  }
