ElevenmxBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: ElevenmxBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreProjet:
            type: string
            length: 255
            column: Titre_Projet
        produit:
            type: string
            length: 255
            column: Produit
        nomGraphiste:
            type: string
            length: 255
            column: Nom_Graphiste
        dateCreationProjet:
            type: string
            length: 255
            column: date_Creation_Projet

    lifecycleCallbacks: {  }

    oneToMany:
        commentaires:
            targetEntity: ElevenmxBundle\Entity\Commentaire
            mappedBy: id
        gestionstatus:
            targetEntity: Gestionstatus
            mappedBy: id


    manyToOne:
        user:
            targetEntity: ElevenmxBundle\Entity\User
            inversedBy: projets

        marque:
            targetEntity: ElevenmxBundle\Entity\Marque
            inversedBy: projets


