ElevenmxBundle\Entity\Projet:
    type: entity
    table: null
    repositoryClass: ElevenmxBundle\Repository\ProjetRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titreProjet:
            type: string
            length: 255
            column: Titre_Projet
        nomGraphiste:
            type: string
            length: 255
            column: Nom_Graphiste
        status:
            type: string
            length: 255
            column: Status
    lifecycleCallbacks: {  }

    oneToMany:
        commentaires:
            targetEntity: ElevenmxBundle\Entity\Commentaire
            mappedBy: id

    manyToOne:
        user:
            targetEntity: ElevenmxBundle\Entity\User
            inversedBy: projets

        marque:
            targetEntity: ElevenmxBundle\Entity\Marque
            inversedBy: projets

        produit:
            targetEntity: ElevenmxBundle\Entity\Produit
            inversedBy: projets
