ElevenmxBundle\Entity\User:
    type: entity
    table: user
    repositoryClass: ElevenmxBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nom:
            type: string
            length: 255
            column: Nom
        prenom:
            type: string
            length: 255
            column: Prenom
        telephone:
            type: string
            length: 255
            column: Telephone
        entreprise:
            type: string
            length: 255
            column: Entreprise
            nullable: true
            required: false
        categorie:
            type: string
            length: 255

    oneToMany:
        projets:
            targetEntity: ElevenmxBundle\Entity\Projet
            mappedBy: user
        users:
            targetEntity: ElevenmxBundle\Entity\User
            mappedBy: id

    oneToMany:
        commentaires:
            targetEntity: ElevenmxBundle\Entity\Commentaire
            mappedBy: id




    lifecycleCallbacks: {  }