gestionstatus_index:
    path:     /
    defaults: { _controller: "ElevenmxBundle:Gestionstatus:index" }
    methods:  GET

gestionstatus_show:
    path:     /{id}/show
    defaults: { _controller: "ElevenmxBundle:Gestionstatus:show" }
    methods:  GET

gestionstatus_new:
    path:     /new
    defaults: { _controller: "ElevenmxBundle:Gestionstatus:new" }
    methods:  [GET, POST]

gestionstatus_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElevenmxBundle:Gestionstatus:edit" }
    methods:  [GET, POST]

gestionstatus_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElevenmxBundle:Gestionstatus:delete" }
    methods:  DELETE
