projet_index:
    path:     /index
    defaults: { _controller: "ElevenmxBundle:Projet:index" }
    methods:  GET

projet_indexGraph:
    path:     /indexGraph
    defaults: { _controller: "ElevenmxBundle:Projet:indexGraph" }
    methods:  GET

projet_indexHisto:
    path:     /indexHisto
    defaults: { _controller: "ElevenmxBundle:Projet:indexHisto" }
    methods:  GET

projet_show:
    path:     /{id}/show
    defaults: { _controller: "ElevenmxBundle:Projet:show" }
    methods:  [GET, POST]

projet_showGraph:
    path:     /{id}/showGraph
    defaults: { _controller: "ElevenmxBundle:Projet:showGraph" }
    methods:  [GET, POST]

projet_new:
    path:     /new
    defaults: { _controller: "ElevenmxBundle:Projet:new" }
    methods:  [GET, POST]

projet_edit:
    path:     /{id}/edit
    defaults: { _controller: "ElevenmxBundle:Projet:edit" }
    methods:  [GET, POST]

projet_editGraph:
    path:     /{id}/editGraph
    defaults: { _controller: "ElevenmxBundle:Projet:editGraph" }
    methods:  [GET, POST]

projet_delete:
    path:     /{id}/delete
    defaults: { _controller: "ElevenmxBundle:Projet:delete" }
    methods:  DELETE

projet_valideBat:
    path:     /{id}/valideBat
    defaults: { _controller: "ElevenmxBundle:Projet:valideBat" }
    methods:  [GET, POST]
